// Code generated by github.com/fragment-dev/fragment-go/v4. DO NOT EDIT.

// Package typed_payloads holds one typed payload per Ledger Entry type and version
// found in your GraphQL operations. Pass them to
// queries.AddTypedLedgerEntries to commit them as one atomic batch.
package typed_payloads

import (
	"github.com/fragment-dev/fragment-go/v4/batch"
	"github.com/fragment-dev/fragment-go/v4/queries"
)

// UserFundsAccountV1Entry is the "user-funds-account" Ledger Entry, version 1.
//
// Fields must be set by name. An unkeyed literal will not compile, which is
// deliberate: two parameters of the same type could otherwise be swapped by
// reordering them, and the mistake would be silent.
type UserFundsAccountV1Entry struct {
	_ struct{}

	// Ik is the idempotency key for this Ledger Entry. It is per entry, not per batch, so a retried batch reports isIkReplay for each entry that had already committed.
	Ik string
	// LedgerIk identifies the Ledger to post this entry to.
	LedgerIk string
	// Posted is an ISO 8601 timestamp, for example "2021-01-01T16:45:00Z". Leave nil to omit it.
	Posted *string
	// Description is also used for this entry's Ledger Lines unless they set their own.
	Description *string
	// Tags attached to this Ledger Entry.
	Tags []queries.LedgerEntryTagInput
	// Groups this Ledger Entry is added to.
	Groups []queries.LedgerEntryGroupInput
	// Conditions that must hold for this Ledger Entry to post. The whole batch rejects if any is not met.
	Conditions []queries.LedgerEntryConditionInput

	Amount string
}

// FragmentBatchEntry marks UserFundsAccountV1Entry as usable in a batch.
func (UserFundsAccountV1Entry) FragmentBatchEntry() {}

// MarshalJSON encodes the entry as an AddLedgerEntryInput.
//
// Fields the caller did not set are omitted rather than sent as null, and
// parameters keep the order they have in the Schema.
func (e UserFundsAccountV1Entry) MarshalJSON() ([]byte, error) {
	ledger := batch.NewObject()
	ledger.Set("ik", e.LedgerIk)
	ledgerJSON, err := ledger.Bytes()
	if err != nil {
		return nil, err
	}

	entry := batch.NewObject()
	entry.SetRaw("ledger", ledgerJSON)
	entry.Set("type", "user-funds-account")
	entry.Set("typeVersion", 1)
	batch.SetOpt(entry, "posted", e.Posted)
	batch.SetOpt(entry, "description", e.Description)
	batch.SetSlice(entry, "tags", e.Tags)
	batch.SetSlice(entry, "groups", e.Groups)
	batch.SetSlice(entry, "conditions", e.Conditions)

	params := batch.NewObject()
	params.Set("amount", e.Amount)
	paramsJSON, err := params.Bytes()
	if err != nil {
		return nil, err
	}
	entry.SetRaw("parameters", paramsJSON)

	entryJSON, err := entry.Bytes()
	if err != nil {
		return nil, err
	}

	out := batch.NewObject()
	out.Set("ik", e.Ik)
	out.SetRaw("entry", entryJSON)
	return out.Bytes()
}

// UserFundsAccountV2Entry is the "user-funds-account" Ledger Entry, version 2.
//
// Fields must be set by name. An unkeyed literal will not compile, which is
// deliberate: two parameters of the same type could otherwise be swapped by
// reordering them, and the mistake would be silent.
type UserFundsAccountV2Entry struct {
	_ struct{}

	// Ik is the idempotency key for this Ledger Entry. It is per entry, not per batch, so a retried batch reports isIkReplay for each entry that had already committed.
	Ik string
	// LedgerIk identifies the Ledger to post this entry to.
	LedgerIk string
	// Posted is an ISO 8601 timestamp, for example "2021-01-01T16:45:00Z". Leave nil to omit it.
	Posted *string
	// Description is also used for this entry's Ledger Lines unless they set their own.
	Description *string
	// Tags attached to this Ledger Entry.
	Tags []queries.LedgerEntryTagInput
	// Groups this Ledger Entry is added to.
	Groups []queries.LedgerEntryGroupInput
	// Conditions that must hold for this Ledger Entry to post. The whole batch rejects if any is not met.
	Conditions []queries.LedgerEntryConditionInput

	Amount    string
	FeeAmount string
}

// FragmentBatchEntry marks UserFundsAccountV2Entry as usable in a batch.
func (UserFundsAccountV2Entry) FragmentBatchEntry() {}

// MarshalJSON encodes the entry as an AddLedgerEntryInput.
//
// Fields the caller did not set are omitted rather than sent as null, and
// parameters keep the order they have in the Schema.
func (e UserFundsAccountV2Entry) MarshalJSON() ([]byte, error) {
	ledger := batch.NewObject()
	ledger.Set("ik", e.LedgerIk)
	ledgerJSON, err := ledger.Bytes()
	if err != nil {
		return nil, err
	}

	entry := batch.NewObject()
	entry.SetRaw("ledger", ledgerJSON)
	entry.Set("type", "user-funds-account")
	entry.Set("typeVersion", 2)
	batch.SetOpt(entry, "posted", e.Posted)
	batch.SetOpt(entry, "description", e.Description)
	batch.SetSlice(entry, "tags", e.Tags)
	batch.SetSlice(entry, "groups", e.Groups)
	batch.SetSlice(entry, "conditions", e.Conditions)

	params := batch.NewObject()
	params.Set("amount", e.Amount)
	params.Set("feeAmount", e.FeeAmount)
	paramsJSON, err := params.Bytes()
	if err != nil {
		return nil, err
	}
	entry.SetRaw("parameters", paramsJSON)

	entryJSON, err := entry.Bytes()
	if err != nil {
		return nil, err
	}

	out := batch.NewObject()
	out.Set("ik", e.Ik)
	out.SetRaw("entry", entryJSON)
	return out.Bytes()
}
