// Code generated by github.com/fragment-dev/fragment-go/v4. DO NOT EDIT.

// Package typed_payloads holds one typed payload per Ledger Entry type and
// version found in your GraphQL operations. Pass them to
// queries.AddTypedLedgerEntries to commit them as one atomic batch.
//
// Set fields by name. An unkeyed literal will not compile, so that two
// parameters of the same type cannot be swapped by reordering them.
//
// Note that tags, groups and conditions use the input types from the SDK's
// queries package, not the package these payloads were generated alongside.
package typed_payloads

import (
	"github.com/fragment-dev/fragment-go/v4/batch"
)

// UserFundsAccountV1Entry is the "user-funds-account" Ledger Entry, version 1.
//
// Fields must be set by name. An unkeyed literal will not compile, which is
// deliberate: two parameters of the same type could otherwise be swapped by
// reordering them, and the mistake would be silent.
type UserFundsAccountV1Entry struct {
	// Prevents an unkeyed composite literal, which would let parameters be
	// supplied positionally.
	_ struct{}

	// Ik is the idempotency key for this Ledger Entry.
	Ik string
	// LedgerIk identifies the Ledger to post this entry to.
	LedgerIk string

	// The parameters of this entry type, in Schema order.

	// Amount is the "amount" parameter.
	Amount string
}

// FragmentBatchEntry marks UserFundsAccountV1Entry as usable in a batch.
func (UserFundsAccountV1Entry) FragmentBatchEntry() {}

// MarshalJSON encodes the entry as an AddLedgerEntryInput.
//
// Fields the caller did not set are omitted rather than sent as null, and
// parameters keep the order they have in the Schema.
func (e UserFundsAccountV1Entry) MarshalJSON() ([]byte, error) {
	ledger := batch.NewObject()
	ledger.Set("ik", e.LedgerIk)

	params := batch.NewObject()
	params.Set("amount", e.Amount)

	entry := batch.NewObject()
	entry.Set("ledger", ledger)
	entry.Set("type", "user-funds-account")
	entry.Set("typeVersion", 1)
	entry.Set("parameters", params)

	out := batch.NewObject()
	out.Set("ik", e.Ik)
	out.Set("entry", entry)
	return out.MarshalJSON()
}

// UserFundsAccountV2Entry is the "user-funds-account" Ledger Entry, version 2.
//
// Fields must be set by name. An unkeyed literal will not compile, which is
// deliberate: two parameters of the same type could otherwise be swapped by
// reordering them, and the mistake would be silent.
type UserFundsAccountV2Entry struct {
	// Prevents an unkeyed composite literal, which would let parameters be
	// supplied positionally.
	_ struct{}

	// Ik is the idempotency key for this Ledger Entry.
	Ik string
	// LedgerIk identifies the Ledger to post this entry to.
	LedgerIk string

	// The parameters of this entry type, in Schema order.

	// Amount is the "amount" parameter.
	Amount string

	// FeeAmount is the "feeAmount" parameter.
	FeeAmount string
}

// FragmentBatchEntry marks UserFundsAccountV2Entry as usable in a batch.
func (UserFundsAccountV2Entry) FragmentBatchEntry() {}

// MarshalJSON encodes the entry as an AddLedgerEntryInput.
//
// Fields the caller did not set are omitted rather than sent as null, and
// parameters keep the order they have in the Schema.
func (e UserFundsAccountV2Entry) MarshalJSON() ([]byte, error) {
	ledger := batch.NewObject()
	ledger.Set("ik", e.LedgerIk)

	params := batch.NewObject()
	params.Set("amount", e.Amount)
	params.Set("feeAmount", e.FeeAmount)

	entry := batch.NewObject()
	entry.Set("ledger", ledger)
	entry.Set("type", "user-funds-account")
	entry.Set("typeVersion", 2)
	entry.Set("parameters", params)

	out := batch.NewObject()
	out.Set("ik", e.Ik)
	out.Set("entry", entry)
	return out.MarshalJSON()
}
