// This file is hand-written. queries.go in this package is generated by
// genqlient and will be overwritten; this file will not.

package queries

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"

	"github.com/fragment-dev/fragment-go/v4/batch"
)

// RawEntry adapts an untyped [AddLedgerEntryInput] so it can be mixed into a
// batch alongside generated typed payloads.
//
// Use it for an entry the generated payloads cannot express: one with lines
// rather than a type, or an entry type missing from your operations.
type RawEntry struct {
	Input AddLedgerEntryInput
}

// FragmentBatchEntry marks RawEntry as usable in a batch.
func (RawEntry) FragmentBatchEntry() {}

// MarshalJSON encodes the wrapped input, omitting fields that were left unset.
//
// The generated input types carry no omitempty, so marshalling one directly
// writes every field the caller did not set as an explicit null. That is not
// merely noisy. A LedgerMatchInput with only ik set encodes as
// {"id":null,"ik":"..."}, which the API resolves as a different Ledger from the
// {"ik":"..."} a typed payload sends — so an entry naming the same Ledger is
// rejected for naming a different one, and a batch cannot mix the two kinds.
//
// Nothing is lost by omitting them. A nil *string in these types means both
// "unset" and "null" with no way to tell them apart, so there is no explicit
// null for a Go caller to have intended. Values inside parameters are passed
// through untouched, since those are the caller's own JSON.
func (r RawEntry) MarshalJSON() ([]byte, error) {
	encoded, err := json.Marshal(r.Input)
	if err != nil {
		return nil, err
	}
	return stripNulls(encoded, map[string]bool{"parameters": true})
}

// stripNulls removes null members from every JSON object in data, recursively.
// The value of any field named in passthrough is kept verbatim.
func stripNulls(data json.RawMessage, passthrough map[string]bool) (json.RawMessage, error) {
	var object map[string]json.RawMessage
	if err := json.Unmarshal(data, &object); err == nil && object != nil {
		kept := make(map[string]json.RawMessage, len(object))
		for name, value := range object {
			if string(value) == "null" {
				continue
			}
			if passthrough[name] {
				kept[name] = value
				continue
			}
			cleaned, err := stripNulls(value, passthrough)
			if err != nil {
				return nil, err
			}
			kept[name] = cleaned
		}
		return json.Marshal(kept)
	}

	var array []json.RawMessage
	if err := json.Unmarshal(data, &array); err == nil && array != nil {
		for i, element := range array {
			cleaned, err := stripNulls(element, passthrough)
			if err != nil {
				return nil, err
			}
			array[i] = cleaned
		}
		return json.Marshal(array)
	}

	// A scalar, or JSON this function has no business rewriting.
	return data, nil
}

type typedBatchVariables struct {
	Entries []batch.Entry `json:"entries"`
}

// AddTypedLedgerEntries commits a batch of Ledger Entries atomically.
//
// Pass generated typed payloads, [RawEntry] values, or a mix of both. Entries are
// posted in the order given and the API returns results in that same order. See
// [AddLedgerEntries] for the untyped equivalent, which takes
// [AddLedgerEntryInput] values directly.
//
// The batch is all-or-nothing: on error nothing was written, so there is no
// partial state to reconcile. Idempotency keys are per entry rather than per
// batch, so retrying a batch that partly succeeded reports IsIkReplay against
// the individual entries that had already committed.
//
// The response is a union. Narrow it before reading results:
//
//	resp, err := queries.AddTypedLedgerEntries(ctx, client, first, second)
//	if err != nil {
//		return err
//	}
//	switch r := resp.GetAddLedgerEntries().(type) {
//	case *queries.AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResult:
//		for _, result := range r.Results {
//			fmt.Println(result.Entry.Ik, result.IsIkReplay)
//		}
//	case *queries.AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesError:
//		// Errors carries one element per failing entry, each with the ik that
//		// identifies which entry to fix.
//		for _, e := range r.Errors {
//			fmt.Println(e.Ik, e.Message)
//		}
//	}
func AddTypedLedgerEntries(
	ctx context.Context,
	client graphql.Client,
	entries ...batch.Entry,
) (*AddLedgerEntriesResponse, error) {
	if entries == nil {
		// Calling with no entries yields a nil slice, which would serialize as
		// null. An empty batch is better expressed as [].
		entries = []batch.Entry{}
	}

	req := &graphql.Request{
		OpName: "AddLedgerEntries",
		Query:  AddLedgerEntries_Operation,
		Variables: &typedBatchVariables{
			Entries: entries,
		},
	}

	data := &AddLedgerEntriesResponse{}
	resp := &graphql.Response{Data: data}

	err := client.MakeRequest(ctx, req, resp)

	return data, err
}
