// Code generated by github.com/fragment-dev/fragment-go/v4. DO NOT EDIT.

// Package typed_payloads holds one typed payload per Ledger Entry type and
// version found in your GraphQL operations. Pass them to
// queries.AddTypedLedgerEntries to commit them as one atomic batch.
//
// Set fields by name. An unkeyed literal will not compile, so that two
// parameters of the same type cannot be swapped by reordering them.
//
// Note that tags, groups and conditions use the input types from the SDK's
// queries package, not the package these payloads were generated alongside.
package typed_payloads

import (
	"github.com/fragment-dev/fragment-go/v4/batch"
)

// OptionalV1Entry is the "optional" Ledger Entry, version 1.
//
// Fields must be set by name. An unkeyed literal will not compile, which is
// deliberate: two parameters of the same type could otherwise be swapped by
// reordering them, and the mistake would be silent.
type OptionalV1Entry struct {
	// Prevents an unkeyed composite literal, which would let parameters be
	// supplied positionally.
	_ struct{}

	// Ik is the idempotency key for this Ledger Entry.
	Ik string
	// LedgerIk identifies the Ledger to post this entry to.
	LedgerIk string
	// Posted is an ISO 8601 timestamp, for example "2021-01-01T16:45:00Z". Leave
	// nil to omit it.
	Posted *string

	// The parameters of this entry type, in Schema order.

	// Required is the "required" parameter.
	Required string

	// Optional is the "optional" parameter. Optional; leave nil to omit it.
	Optional *string
}

// FragmentBatchEntry marks OptionalV1Entry as usable in a batch.
func (OptionalV1Entry) FragmentBatchEntry() {}

// MarshalJSON encodes the entry as an AddLedgerEntryInput.
//
// Fields the caller did not set are omitted rather than sent as null, and
// parameters keep the order they have in the Schema.
func (e OptionalV1Entry) MarshalJSON() ([]byte, error) {
	ledger := batch.NewObject()
	ledger.Set("ik", e.LedgerIk)

	params := batch.NewObject()
	params.Set("required", e.Required)
	batch.SetOpt(params, "optional", e.Optional)

	entry := batch.NewObject()
	entry.Set("ledger", ledger)
	entry.Set("type", "optional")
	entry.Set("typeVersion", 1)
	batch.SetOpt(entry, "posted", e.Posted)
	entry.Set("parameters", params)

	out := batch.NewObject()
	out.Set("ik", e.Ik)
	out.Set("entry", entry)
	return out.MarshalJSON()
}
