package typedentries

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// PackageName is the package the typed payloads are generated into. They go in
// a package of their own, separate from whatever the caller's code lives in,
// because that is what makes the keyed-literal requirement enforceable: Go only
// rejects an unkeyed composite literal that assigns to an unexported field when
// the literal is written outside the type's own package.
const PackageName = "typed_payloads"

// queriesImport is where the generated payloads find the shared input types
// (tags, groups, conditions). Those are Schema types, identical in every
// generated package, so the payloads use the SDK's copy rather than the
// caller's, whose import path is not knowable from the generator's arguments.
const moduleImport = "github.com/fragment-dev/fragment-go/v4"

const queriesImport = moduleImport + "/queries"

const batchImport = moduleImport + "/batch"

// commonFieldDecls are emitted on every payload, in this order. See
// commonFields for why the set is fixed rather than derived.
var commonFieldDecls = []struct {
	Name, Type, Wire, Doc string
}{
	{"Ik", "string", "", "Ik is the idempotency key for this Ledger Entry. It is per entry, not per batch, so a retried batch reports isIkReplay for each entry that had already committed."},
	{"LedgerIk", "string", "", "LedgerIk identifies the Ledger to post this entry to."},
	{"Posted", "*string", "posted", "Posted is an ISO 8601 timestamp, for example \"2021-01-01T16:45:00Z\". Leave nil to omit it."},
	{"Description", "*string", "description", "Description is also used for this entry's Ledger Lines unless they set their own."},
	{"Tags", "[]queries.LedgerEntryTagInput", "tags", "Tags attached to this Ledger Entry."},
	{"Groups", "[]queries.LedgerEntryGroupInput", "groups", "Groups this Ledger Entry is added to."},
	{"Conditions", "[]queries.LedgerEntryConditionInput", "conditions", "Conditions that must hold for this Ledger Entry to post. The whole batch rejects if any is not met."},
}

// Emit renders the typed payloads as a formatted Go source file. It returns nil
// when there is nothing to generate.
func Emit(payloads []Payload) ([]byte, error) {
	if len(payloads) == 0 {
		return nil, nil
	}

	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by %s. DO NOT EDIT.\n\n", moduleImport)
	fmt.Fprintf(&b, "// Package %s holds one typed payload per Ledger Entry type and version\n", PackageName)
	fmt.Fprintf(&b, "// found in your GraphQL operations. Pass them to\n")
	fmt.Fprintf(&b, "// queries.AddTypedLedgerEntries to commit them as one atomic batch.\n")
	fmt.Fprintf(&b, "package %s\n\n", PackageName)

	b.WriteString("import (\n")
	if needsJSON(payloads) {
		b.WriteString("\t\"encoding/json\"\n\n")
	}
	fmt.Fprintf(&b, "\t%q\n", batchImport)
	fmt.Fprintf(&b, "\t%q\n", queriesImport)
	b.WriteString(")\n")

	for _, p := range payloads {
		emitPayload(&b, p)
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		// Return the unformatted source alongside the error; it is far easier
		// to diagnose a generator bug by reading what it produced.
		return nil, fmt.Errorf("formatting generated source: %w\n\n%s", err, b.String())
	}
	return out, nil
}

// needsJSON reports whether the generated file references encoding/json, which
// happens either for an untyped payload's raw Parameters field or for a
// parameter bound to a JSON scalar.
func needsJSON(payloads []Payload) bool {
	for _, p := range payloads {
		if p.Untyped {
			return true
		}
		for _, param := range p.Params {
			if strings.Contains(param.GoType, "json.") {
				return true
			}
		}
	}
	return false
}

func emitPayload(b *bytes.Buffer, p Payload) {
	fmt.Fprintf(b, "\n// %s is the %q Ledger Entry, version %d.\n", p.GoName, p.Type, p.TypeVersion)
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// Fields must be set by name. An unkeyed literal will not compile, which is\n")
	fmt.Fprintf(b, "// deliberate: two parameters of the same type could otherwise be swapped by\n")
	fmt.Fprintf(b, "// reordering them, and the mistake would be silent.\n")
	fmt.Fprintf(b, "type %s struct {\n", p.GoName)
	b.WriteString("\t_ struct{}\n\n")

	for _, f := range commonFieldDecls {
		fmt.Fprintf(b, "\t// %s\n", f.Doc)
		fmt.Fprintf(b, "\t%s %s\n", f.Name, f.Type)
	}

	if p.Untyped {
		b.WriteString("\n\t// Parameters for this entry type could not be typed from the source\n")
		b.WriteString("\t// operation, which did not bind them individually. Supply encoded JSON.\n")
		b.WriteString("\tParameters json.RawMessage\n")
	}

	if len(p.Params) > 0 {
		b.WriteString("\n")
	}
	for _, param := range p.Params {
		// Only comment a parameter when there is something to say: that its Go
		// field name differs from the name it travels under, or that it may be
		// left unset.
		renamed := exportedIdent(param.WireName) != param.FieldName
		if renamed {
			fmt.Fprintf(b, "\t// %s is the %q parameter, renamed to avoid a collision.\n", param.FieldName, param.WireName)
		}
		if !param.Required {
			if renamed {
				b.WriteString("\t//\n")
			}
			fmt.Fprintf(b, "\t// Optional; leave nil to omit it.\n")
		}
		fmt.Fprintf(b, "\t%s %s\n", param.FieldName, param.GoType)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "// FragmentBatchEntry marks %s as usable in a batch.\n", p.GoName)
	fmt.Fprintf(b, "func (%s) FragmentBatchEntry() {}\n\n", p.GoName)

	emitMarshal(b, p)
}

func emitMarshal(b *bytes.Buffer, p Payload) {
	fmt.Fprintf(b, "// MarshalJSON encodes the entry as an AddLedgerEntryInput.\n")
	fmt.Fprintf(b, "//\n")
	fmt.Fprintf(b, "// Fields the caller did not set are omitted rather than sent as null, and\n")
	fmt.Fprintf(b, "// parameters keep the order they have in the Schema.\n")
	fmt.Fprintf(b, "func (e %s) MarshalJSON() ([]byte, error) {\n", p.GoName)

	b.WriteString("\tledger := batch.NewObject()\n")
	b.WriteString("\tledger.Set(\"ik\", e.LedgerIk)\n")
	b.WriteString("\tledgerJSON, err := ledger.Bytes()\n")
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")

	b.WriteString("\tentry := batch.NewObject()\n")
	b.WriteString("\tentry.SetRaw(\"ledger\", ledgerJSON)\n")
	fmt.Fprintf(b, "\tentry.Set(\"type\", %q)\n", p.Type)
	fmt.Fprintf(b, "\tentry.Set(\"typeVersion\", %d)\n", p.TypeVersion)

	for _, f := range commonFieldDecls {
		if f.Wire == "" {
			continue
		}
		switch {
		case f.Type[0] == '*':
			fmt.Fprintf(b, "\tbatch.SetOpt(entry, %q, e.%s)\n", f.Wire, f.Name)
		default:
			fmt.Fprintf(b, "\tbatch.SetSlice(entry, %q, e.%s)\n", f.Wire, f.Name)
		}
	}
	b.WriteString("\n")

	if p.Untyped {
		b.WriteString("\tif e.Parameters != nil {\n")
		b.WriteString("\t\tentry.SetRaw(\"parameters\", e.Parameters)\n")
		b.WriteString("\t}\n\n")
	} else {
		b.WriteString("\tparams := batch.NewObject()\n")
		for _, param := range p.Params {
			if param.Required {
				fmt.Fprintf(b, "\tparams.Set(%q, e.%s)\n", param.WireName, param.FieldName)
			} else {
				fmt.Fprintf(b, "\tbatch.SetOpt(params, %q, e.%s)\n", param.WireName, param.FieldName)
			}
		}
		b.WriteString("\tparamsJSON, err := params.Bytes()\n")
		b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		b.WriteString("\tentry.SetRaw(\"parameters\", paramsJSON)\n\n")
	}

	b.WriteString("\tentryJSON, err := entry.Bytes()\n")
	b.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n\n")

	b.WriteString("\tout := batch.NewObject()\n")
	b.WriteString("\tout.Set(\"ik\", e.Ik)\n")
	b.WriteString("\tout.SetRaw(\"entry\", entryJSON)\n")
	b.WriteString("\treturn out.Bytes()\n")
	b.WriteString("}\n")
}
