package typedentries

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// PackageName is the package the typed payloads are generated into. They go in
// a package of their own, separate from whatever the caller's code lives in,
// because that is what makes the keyed-literal requirement enforceable: Go only
// rejects an unkeyed composite literal that assigns to an unexported field when
// the literal is written outside the type's own package.
const PackageName = "typed_payloads"

const (
	moduleImport = "github.com/fragment-dev/fragment-go/v4"
	// queriesImport is where the generated payloads find the shared input types
	// for tags, groups and conditions.
	//
	// One codegen run writes two packages: genqlient's client, into --output with
	// the name given by --package, and these payloads into a typed_payloads
	// package beside it. The payloads cannot import that sibling — the generator
	// knows its package name but not its import path, since nothing on the
	// command line gives it one — so they use the SDK's own copy of these Schema
	// types instead.
	queriesImport = moduleImport + "/queries"
	batchImport   = moduleImport + "/batch"
)

// commentWidth is where doc comments wrap. gofmt does not reflow comments, so a
// generator that does not wrap produces lines that run off the edge in both the
// source file and go doc output.
const commentWidth = 76

// Emit renders the typed payloads as a formatted Go source file. It returns nil
// when there is nothing to generate.
func Emit(payloads []Payload) ([]byte, error) {
	if len(payloads) == 0 {
		return nil, nil
	}

	var b bytes.Buffer

	fmt.Fprintf(&b, "// Code generated by %s. DO NOT EDIT.\n\n", moduleImport)
	comment(&b, "", fmt.Sprintf(
		"Package %s holds one typed payload per Ledger Entry type and version found in your GraphQL operations. Pass them to queries.AddTypedLedgerEntries to commit them as one atomic batch.",
		PackageName))
	comment(&b, "", "")
	comment(&b, "", "Set fields by name. An unkeyed literal will not compile, so that two parameters of the same type cannot be swapped by reordering them.")
	comment(&b, "", "")
	comment(&b, "", "Note that tags, groups and conditions use the input types from the SDK's queries package, not the package these payloads were generated alongside.")
	fmt.Fprintf(&b, "package %s\n\n", PackageName)

	b.WriteString("import (\n")
	if needsJSON(payloads) {
		b.WriteString("\t\"encoding/json\"\n\n")
	}
	fmt.Fprintf(&b, "\t%q\n", batchImport)
	fmt.Fprintf(&b, "\t%q\n", queriesImport)
	b.WriteString(")\n")

	for _, p := range payloads {
		emitPayload(&b, p)
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		// Return the unformatted source alongside the error; it is far easier
		// to diagnose a generator bug by reading what it produced.
		return nil, fmt.Errorf("formatting generated source: %w\n\n%s", err, b.String())
	}
	return out, nil
}

// comment writes a doc comment, wrapped to commentWidth. An empty text produces
// a bare "//", the blank line between paragraphs.
func comment(b *bytes.Buffer, indent, text string) {
	if text == "" {
		fmt.Fprintf(b, "%s//\n", indent)
		return
	}

	line := ""
	for _, word := range strings.Fields(text) {
		switch {
		case line == "":
			line = word
		case len(line)+1+len(word) <= commentWidth:
			line += " " + word
		default:
			fmt.Fprintf(b, "%s// %s\n", indent, line)
			line = word
		}
	}
	if line != "" {
		fmt.Fprintf(b, "%s// %s\n", indent, line)
	}
}

// needsJSON reports whether the generated file references encoding/json, which
// happens for an untyped payload's raw Parameters field, for a parameter bound to
// a JSON scalar, and for a non-scalar parameter that fell back to raw JSON.
func needsJSON(payloads []Payload) bool {
	for _, p := range payloads {
		if p.Untyped {
			return true
		}
		for _, param := range p.Params {
			if strings.Contains(param.GoType, "json.") {
				return true
			}
		}
	}
	return false
}

func emitPayload(b *bytes.Buffer, p Payload) {
	b.WriteString("\n")
	comment(b, "", fmt.Sprintf("%s is the %q Ledger Entry, version %d.", p.GoName, p.Type, p.TypeVersion))
	comment(b, "", "")
	comment(b, "", "Fields must be set by name. An unkeyed literal will not compile, which is deliberate: two parameters of the same type could otherwise be swapped by reordering them, and the mistake would be silent.")
	fmt.Fprintf(b, "type %s struct {\n", p.GoName)

	comment(b, "\t", "Prevents an unkeyed composite literal, which would let parameters be supplied positionally.")
	b.WriteString("\t_ struct{}\n\n")

	for _, f := range CommonFields {
		comment(b, "\t", f.Doc)
		fmt.Fprintf(b, "\t%s %s\n", f.Name, f.Type)
	}
	if p.Lines {
		comment(b, "\t", linesField.Doc)
		fmt.Fprintf(b, "\t%s %s\n", linesField.Name, linesField.Type)
	}

	if p.Untyped {
		b.WriteString("\n")
		comment(b, "\t", "Parameters for this entry type could not be typed from the source operation, which did not bind them individually. Supply encoded JSON, or leave nil to omit it.")
		b.WriteString("\tParameters json.RawMessage\n")
	}

	if len(p.Params) > 0 {
		b.WriteString("\n")
		comment(b, "\t", "The parameters of this entry type, in Schema order.")
		b.WriteString("\n")
	}
	for i, param := range p.Params {
		if i > 0 {
			b.WriteString("\n")
		}
		comment(b, "\t", paramDoc(param))
		fmt.Fprintf(b, "\t%s %s\n", param.FieldName, param.GoType)
	}
	b.WriteString("}\n\n")

	comment(b, "", fmt.Sprintf("FragmentBatchEntry marks %s as usable in a batch.", p.GoName))
	fmt.Fprintf(b, "func (%s) FragmentBatchEntry() {}\n\n", p.GoName)

	emitMarshal(b, p)
}

// Generate the doc comment for a parameter, including its original name from the
// Schema and its optionality. Parameters can be rename to avoid collisions.
func paramDoc(param Param) string {
	doc := fmt.Sprintf("%s is the %q parameter.", param.FieldName, param.WireName)

	if escaped := exportedIdent(param.WireName); escaped != param.FieldName {
		// Say what it collided with. A clash with a common field and a clash
		// with another parameter call for very different reactions.
		if isReserved(escaped) {
			doc += fmt.Sprintf(" It is not %s, which is a field every entry carries; the parameter is renamed because that name is taken.", escaped)
		} else {
			doc += fmt.Sprintf(" It is renamed from %s, which another parameter of this entry type already uses.", escaped)
		}
	}

	if param.Kind != KindValue {
		doc += " Optional; leave nil to omit it."
	}
	return doc
}

func isReserved(name string) bool {
	for _, reserved := range reservedFieldNames {
		if name == reserved {
			return true
		}
	}
	return false
}

func emitMarshal(b *bytes.Buffer, p Payload) {
	comment(b, "", "MarshalJSON encodes the entry as an AddLedgerEntryInput.")
	comment(b, "", "")
	comment(b, "", "Fields the caller did not set are omitted rather than sent as null, and parameters keep the order they have in the Schema.")
	fmt.Fprintf(b, "func (e %s) MarshalJSON() ([]byte, error) {\n", p.GoName)

	b.WriteString("\tledger := batch.NewObject()\n")
	b.WriteString("\tledger.Set(\"ik\", e.LedgerIk)\n\n")

	if !p.Untyped {
		b.WriteString("\tparams := batch.NewObject()\n")
		for _, param := range p.Params {
			setField(b, "params", param.WireName, "e."+param.FieldName, param.Kind)
		}
		b.WriteString("\n")
	}

	b.WriteString("\tentry := batch.NewObject()\n")
	b.WriteString("\tentry.Set(\"ledger\", ledger)\n")
	fmt.Fprintf(b, "\tentry.Set(\"type\", %q)\n", p.Type)
	fmt.Fprintf(b, "\tentry.Set(\"typeVersion\", %d)\n", p.TypeVersion)
	for _, f := range CommonFields {
		if f.Wire == "" {
			continue
		}
		setField(b, "entry", f.Wire, "e."+f.Name, f.Kind)
	}
	if p.Lines {
		setField(b, "entry", linesField.Wire, "e."+linesField.Name, linesField.Kind)
	}
	if p.Untyped {
		setField(b, "entry", "parameters", "e.Parameters", KindRaw)
	} else {
		b.WriteString("\tentry.Set(\"parameters\", params)\n")
	}
	b.WriteString("\n")

	b.WriteString("\tout := batch.NewObject()\n")
	b.WriteString("\tout.Set(\"ik\", e.Ik)\n")
	b.WriteString("\tout.Set(\"entry\", entry)\n")
	b.WriteString("\treturn out.MarshalJSON()\n")
	b.WriteString("}\n")
}

// setField writes the call that adds one field, choosing the helper by the shape
// of the Go type. Dispatching on the shape rather than on whether the Schema
// marked the field required is what keeps a nullable list, which is a slice and
// not a pointer, from being handed to the pointer helper.
func setField(b *bytes.Buffer, object, wire, expr string, kind ParamKind) {
	switch kind {
	case KindPointer:
		fmt.Fprintf(b, "\tbatch.SetOpt(%s, %q, %s)\n", object, wire, expr)
	case KindSlice:
		fmt.Fprintf(b, "\tbatch.SetSlice(%s, %q, %s)\n", object, wire, expr)
	case KindRaw:
		// Raw JSON is a []byte, so it cannot go through the generic slice
		// helper, which would marshal it as base64.
		fmt.Fprintf(b, "\tif %s != nil {\n", expr)
		fmt.Fprintf(b, "\t\t%s.Set(%q, %s)\n", object, wire, expr)
		b.WriteString("\t}\n")
	default:
		fmt.Fprintf(b, "\t%s.Set(%q, %s)\n", object, wire, expr)
	}
}
