on:
  workflow_dispatch:

name: Update SDK queries
jobs:
  updateQueries:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.PR_APP_ID }}
          private_key: ${{ secrets.PR_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          path: graphql-queries
          repository: fragment-dev/graphql-queries
          token: ${{ steps.generate-token.outputs.token }}

      - uses: actions/checkout@v4
        name: Checkout fragment-go
        with:
          path: fragment-go

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
        id: go

      - name: Copy queries.graphql
        working-directory: ./fragment-go
        run: |
          cp ../graphql-queries/queries.graphql queries/queries.graphql

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Capitalize GraphQL queries in queries.graphql
        working-directory: ./fragment-go
        run: |
          python format_queries.py

      - name: Validate GraphQL queries
        working-directory: ./fragment-go
        run: |
          export EXITCODE=$(grep -E '^(mutation|query) [a-z]' queries/queries.graphql || echo $?)
          if [[ $EXITCODE -eq 0 ]]; then
            echo "Failed to validate queries."
            echo "Ensure that queries are in TitleCase."
            exit 1
          fi

      - name: Build
        working-directory: ./fragment-go
        run: |
          go run main.go \
            --input=queries/queries.graphql \
            --output=queries/queries.go \
            --package=queries

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: ./fragment-go
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: 'Update Go SDK queries'
          title: 'Update Go SDK queries'
          base: 'dev'
          branch: update-sdk-queries/${{ github.run_id }}
          body: >
            This PR is auto-generated by github action.
